### PR TITLE
Fix style errors

### PR DESCRIPTION
**Pull request by RDIL**
## Description  
Fixes style errors
Needs review

### CODE REVIEW

**Comment by N8python** [comment]
What will the styling fix do?

**Comment by RDIL** [comment]
Just make it so we can use ESLint

**Comment by RDIL** [comment]
@N8python from now on we need to follow these style guides.

**Comment by RDIL** [comment]
Still got 115 issues to fix @N8python LOL

**Comment by RDIL** [comment]
@N8python can you look over my changes and see if I made any mistakes?

**Pull request merged**
