### PR TITLE
bug fix?

### PR DESCRIPTION
**Pull request by RDIL**
## Description  
@N8python please review

### CODE REVIEW

**Comment by N8python** [comment]
I looked at it

**Comment by RDIL** [comment]
@N8python was the `+` there for a reason?  I thought it was a typo.

**Comment by N8python** [comment]
Thanks for spotting some code issues. However it worked fine before, and I don't think we'll need to add them.

**Comment by RDIL** [comment]
@N8python the first change was just linting, it was the extra `+` I was worried about

**Comment by RDIL** [comment]
@N8python how is [this](https://rdil.rocks/depression/issue.png) not an issue?

**Comment by N8python** [comment]
The extra + is there because I got that function from someone else. They made the function. so I'm sure there is a plsu there for a reason

**Comment by N8python** [comment]
The unary plus operator just converts something to an integer:
```js
"1" + 1 //11
+"1" + 1 //2
```

**Comment by RDIL** [comment]
@N8python I fixed the stuff, ill merge now

**Pull request merged**
